name: Testing output
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.step1.outputs.test}}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - env:
          OUTPUT1: ${{needs.first-job.outputs.output1}}
        run: echo '$OUTPUT1'
